cc_test(
	name = "parser_test",
    size = "medium",
    srcs = ["parser_test.cc"],
    deps = [
    	"@com_google_googletest//:gtest_main",
		"//winzigc/frontend/parser:parser_lib",
		"//winzigc/frontend/syntax:token_lib",
    ],
)