cc_test(
    name = "semantic_test",
    size = "medium",
    srcs = ["semantic_test.cc"],
    deps = [
        "//winzigc/frontend/lexer:lexer_lib",
        "//winzigc/frontend/parser:parser_lib",
        "//winzigc/visitor/semantic:semantic_lib",
        "@com_google_googletest//:gtest_main",
    ],
)
