cc_test(
    name = "lexer_test",
    size = "small",
    srcs = ["lexer_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//winzigc/frontend/lexer:lexer_lib",
        "//winzigc/frontend/syntax:token_lib",
    ],
)
