load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ast_lib",
    hdrs = [
        "expr.h",
        "statement.h",
        "type.h",
        "var.h",
        "function.h",
        "program.h",
    ],
    visibility = ["//winzigc/frontend/parser:__pkg__"],
)
