load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "pure_lib",
    hdrs = [
        "pure.h",
    ],
    visibility = [
        "//winzigc/visitor/codegen:__pkg__",
        "//winzigc/frontend/ast:__pkg__",
    ],
)
